import { getMyProfile } from '@/features/employee-self-service/queries';

const date = (value: Date | null | undefined) => value ? value.toISOString().slice(0, 10) : '—';
const clock = (seconds: number | null) => seconds == null ? '—' : `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor((seconds % 3600) / 60)).padStart(2, '0')}`;
const weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export default async function MyProfilePage() {
  const profile = await getMyProfile();
  if (!profile) return null;
  const employment = profile.employee.employmentRecords[0];
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Employee Self-Service</p><h1 className="text-2xl font-black">My Profile</h1><p className="text-sm text-slate-500">HR-controlled information is read-only.</p></div>
    <section className="rounded-3xl border bg-white p-6"><dl className="grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Name</dt><dd className="font-bold">{profile.employee.firstName} {profile.employee.lastName}</dd></div><div><dt className="text-slate-500">Employee number</dt><dd className="font-bold">{profile.employee.employeeNumber}</dd></div><div><dt className="text-slate-500">Employee status</dt><dd className="font-bold">{profile.employee.employeeStatus}</dd></div><div><dt className="text-slate-500">Contact email</dt><dd className="font-bold">{profile.employee.email}</dd></div><div><dt className="text-slate-500">Login email</dt><dd className="font-bold">{profile.loginEmail}</dd></div><div><dt className="text-slate-500">Phone</dt><dd className="font-bold">{profile.employee.phone}</dd></div><div><dt className="text-slate-500">Position</dt><dd className="font-bold">{employment?.jobTitle ?? '—'}</dd></div><div><dt className="text-slate-500">Department</dt><dd className="font-bold">{employment?.department ?? '—'}</dd></div><div><dt className="text-slate-500">Category / Classification</dt><dd className="font-bold">{employment ? `${employment.employmentCategory} / ${employment.employmentStatus}` : '—'}</dd></div><div><dt className="text-slate-500">Employment type</dt><dd className="font-bold">{employment?.employmentType ?? '—'}</dd></div><div><dt className="text-slate-500">Hire / Start</dt><dd className="font-bold">{date(employment?.hireDate)} / {date(employment?.startDate)}</dd></div><div><dt className="text-slate-500">Effective period</dt><dd className="font-bold">{date(employment?.effectiveFrom)} – {date(employment?.effectiveTo)}</dd></div>{employment?.probation && <div><dt className="text-slate-500">Probation expected end</dt><dd className="font-bold">{date(employment.probation.expectedEndAt)}</dd></div>}</dl></section>
    <section className="rounded-3xl border bg-white p-6"><h2 className="font-bold">Current Work Schedule</h2><p className="mt-1 text-sm text-slate-500">{profile.schedule?.name ?? 'No current schedule assigned'}</p>{profile.schedule && <div className="mt-4 space-y-2">{profile.schedule.days.map((day) => <div key={day.isoWeekday} className="grid gap-2 rounded-xl bg-slate-50 p-3 text-sm sm:grid-cols-3"><strong>{weekdays[day.isoWeekday - 1]}</strong><span>{day.isWorkday ? `${clock(day.expectedStartSecond)}–${clock(day.expectedEndSecond)}` : 'Rest day'}</span><span className="text-slate-500">{day.breaks.map((item) => `${clock(item.startSecond)}–${clock(item.endSecond)} ${item.isPaid ? 'paid' : 'unpaid'}`).join(', ') || 'No break'}</span></div>)}</div>}</section>
  </div>;
}
