import { redirect } from 'next/navigation';
import { logoutAction } from '@/lib/auth/actions';
import { EmployeeSelfAccessError, requireEmployeeSelfContext } from '@/features/employee-self-service/context';
import { getOrganizationBranding } from '@/features/organization-branding/read-model';
import { TenantTheme } from '@/components/layout/TenantTheme';
import { EmployeeNav } from '@/components/employee-self-service/EmployeeNav';
import { TenantLogo } from '@/components/layout/TenantLogo';

export default async function EmployeeLayout({ children }: { children: React.ReactNode }) {
  let context; try { context = await requireEmployeeSelfContext(); } catch (error) { if (error instanceof EmployeeSelfAccessError && error.code === 'FORBIDDEN') redirect('/dashboard'); redirect('/login?access=unavailable'); }
  const brand = await getOrganizationBranding(context.organization.id); if (!brand) redirect('/login');
  return <TenantTheme branding={brand}><div className="wp-tenant-shell min-h-screen text-[var(--wp-text)]"><header className="wp-tenant-rule flex items-center gap-3 border-b bg-white px-5 py-3 md:hidden"><TenantLogo branding={brand} size={36} className="h-9 w-9 rounded-md bg-white object-contain" fallbackClassName="flex h-9 w-9 items-center justify-center rounded-md bg-[var(--tenant-primary)] text-xs font-black text-[var(--tenant-primary-foreground)]" /><div><b className="block truncate">{brand.displayName}</b><span className="text-[9px] font-bold uppercase tracking-wider text-[var(--tenant-accent)]">WorkPulse</span></div></header><div className="mx-auto flex max-w-[92rem]"><aside className="wp-tenant-sidebar sticky top-0 hidden h-screen w-60 shrink-0 flex-col border-r md:flex"><div className="wp-tenant-rule border-b p-5"><div className="flex items-center gap-3"><TenantLogo branding={brand} size={40} className="h-10 w-10 rounded-md bg-white object-contain" fallbackClassName="flex h-10 w-10 items-center justify-center rounded-md bg-[var(--tenant-primary)] text-xs font-black text-[var(--tenant-primary-foreground)]" /><p className="min-w-0 truncate font-bold">{brand.displayName}</p></div><p className="mt-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--tenant-accent)]">Employee self-service · WorkPulse</p></div><div className="flex-1"><EmployeeNav /></div><div className="wp-tenant-rule border-t p-4"><p className="truncate text-sm font-bold">{context.employee.firstName} {context.employee.lastName}</p><p className="truncate text-xs text-[var(--wp-text-muted)]">{context.employee.employeeNumber}</p><form action={logoutAction}><button className="mt-3 text-xs font-bold text-[var(--wp-danger)]">Sign out</button></form></div></aside><main className="w-full min-w-0 p-5 sm:p-7 lg:p-9">{children}</main></div></div></TenantTheme>;
}
