'use client';

import { useState, useTransition } from 'react';
import { cancelApprovedLeaveAction, configureSagaLeavePolicyAction, createLeaveCycleAction, createLeaveTypeAction, deactivateLeaveTypeAction, grantCycleEntitlementsAction, reviewLeaveRequestAction, retryLeaveAttendanceSyncAction } from '@/features/leave/hr-actions';

interface AdminRequest { id: string; type: string; typeCode: string; category: string | null; from: string; to: string; units: number; reason: string; status: string; attendanceSyncStatus: string; employee: { employeeNumber: string; firstName: string; lastName: string }; documents: Array<{ id: string; fileName: string; kindCode: string }> }
interface AdminType { id: string; name: string; balanceTracked: boolean; defaultGrantUnits: number | null; cycles: Array<{ id: string; name: string }> }

export function LeaveAdminPanel({ requests, types, employees }: { requests: AdminRequest[]; types: AdminType[]; employees: Array<{ id: string; employeeNumber: string; firstName: string; lastName: string }> }) {
  const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const run = (operation: () => Promise<unknown>) => startTransition(async () => { const result = await operation(); const error = typeof result === 'object' && result !== null && 'error' in result ? String(result.error) : null; setMessage(error ?? 'Leave operation completed.'); });
  const approve = (request: AdminRequest) => {
    if (!window.confirm('Confirm that this employee satisfies every configured eligibility rule for this request.')) return;
    const eligibilityChecks: Record<string, boolean> = { ELIGIBILITY_CONFIRMED: true };
    if (request.typeCode === 'MATERNITY') {
      if (!window.confirm('Explicitly confirm that SSS approval/support and the required maternity documentation or HR verification were checked.')) return;
      eligibilityChecks.SSS_SUPPORT_CONFIRMED = true;
      eligibilityChecks.DOCUMENT_SSS_SUPPORT_VERIFIED = true;
    }
    run(() => reviewLeaveRequestAction({ requestId: request.id, decision: 'APPROVE', remarks: 'Approved after policy and eligibility review.', eligibilityChecks }));
  };
  return <div className="space-y-6">{message && <p className="rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}
    <section className="rounded-3xl border bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Leave policy configuration</h2><p className="text-xs text-slate-500">SAGA setup is explicit and idempotent; it never grants balances.</p></div><button onClick={() => run(() => configureSagaLeavePolicyAction(new Date().getFullYear(), true))} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Configure SAGA policy</button></div>
      <form className="mt-4 grid gap-2 md:grid-cols-3" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); run(() => createLeaveTypeAction({ code: String(f.get('code')), name: String(f.get('name')), description: String(f.get('description')), isPaid: f.get('paid') === 'on', countingMode: String(f.get('mode')) as 'SCHEDULED_WORK_DAYS' | 'CALENDAR_DAYS', balanceTracked: f.get('tracked') === 'on', defaultGrantUnits: f.get('grant') ? Number(f.get('grant')) : null, policyReference: String(f.get('reference')) })); }}><input name="code" required placeholder="Code" className="rounded-xl border p-2" /><input name="name" required placeholder="Name" className="rounded-xl border p-2" /><input name="description" placeholder="Description" className="rounded-xl border p-2" /><select name="mode" className="rounded-xl border p-2"><option value="SCHEDULED_WORK_DAYS">Scheduled workdays</option><option value="CALENDAR_DAYS">Calendar days</option></select><input name="grant" type="number" min="0" step="0.0001" placeholder="Default grant" className="rounded-xl border p-2" /><input name="reference" required placeholder="Policy reference" className="rounded-xl border p-2" /><label><input type="checkbox" name="paid" /> Paid</label><label><input type="checkbox" name="tracked" /> Balance tracked</label><button className="rounded-xl border p-2 font-bold">Create leave type</button></form>
      <div className="mt-4 space-y-2">{types.map((type) => <div key={type.id} className="rounded-xl bg-slate-50 p-3 text-sm"><div className="flex justify-between"><strong>{type.name}</strong><button onClick={() => run(() => deactivateLeaveTypeAction(type.id, true))} className="text-rose-700">Deactivate</button></div><form className="mt-2 flex flex-wrap gap-2" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); run(() => createLeaveCycleAction({ leaveTypeId: type.id, code: String(f.get('code')), name: String(f.get('name')), startDate: String(f.get('start')), endDate: String(f.get('end')) })); }}><input name="code" required placeholder="Cycle code" className="rounded border p-1" /><input name="name" required placeholder="Cycle name" className="rounded border p-1" /><input name="start" required type="date" className="rounded border p-1" /><input name="end" required type="date" className="rounded border p-1" /><button className="rounded border px-2">Add cycle</button></form></div>)}</div>
    </section>
    <section className="rounded-3xl border bg-white p-6"><h2 className="font-bold">Grant cycle entitlement</h2><form className="mt-4 grid gap-3 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const type = types.find((item) => item.id === form.get('type')); if (!type) return; const eligibilityConfirmed = window.confirm('Confirm HR checked this employee against the configured eligibility rules before creating the immutable grant.'); if (!eligibilityConfirmed) return; run(() => grantCycleEntitlementsAction({ leaveTypeId: type.id, leaveCycleId: String(form.get('cycle')), employeeIds: [String(form.get('employee'))], reason: String(form.get('reason')), confirmed: true, eligibilityConfirmed })); }}><select name="type" className="rounded-xl border p-2">{types.filter((item) => item.balanceTracked).map((item) => <option key={item.id} value={item.id}>{item.name} ({item.defaultGrantUnits})</option>)}</select><select name="cycle" className="rounded-xl border p-2">{types.flatMap((item) => item.cycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{item.name} · {cycle.name}</option>))}</select><select name="employee" className="rounded-xl border p-2">{employees.map((item) => <option key={item.id} value={item.id}>{item.employeeNumber} · {item.firstName} {item.lastName}</option>)}</select><input name="reason" required placeholder="Grant reason" className="rounded-xl border p-2" /><button disabled={pending} className="rounded-xl bg-slate-900 p-2 font-bold text-white md:col-span-4">Grant entitlement</button></form></section>
    <section className="space-y-3"><h2 className="font-bold">Leave requests</h2>{requests.map((request) => <article key={request.id} className="rounded-2xl border bg-white p-5 text-sm"><div className="flex flex-wrap justify-between gap-3"><div><strong>{request.employee.firstName} {request.employee.lastName}</strong> · {request.employee.employeeNumber}<p>{request.type}{request.category ? ` · ${request.category}` : ''} · {request.from}–{request.to} · {request.units} unit(s)</p><p className="mt-1 text-slate-500">{request.reason}</p>{request.documents.map((doc) => <a className="mr-2 text-blue-700 underline" key={doc.id} href={`/api/leave-documents/${doc.id}`}>{doc.kindCode}: {doc.fileName}</a>)}</div><span className="font-bold">{request.status}</span></div>
      {request.status === 'PENDING' && <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => approve(request)} className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">Approve with verification</button><button onClick={() => { const remarks = prompt('Rejection remarks'); if (remarks) run(() => reviewLeaveRequestAction({ requestId: request.id, decision: 'REJECT', remarks })); }} className="rounded-xl border px-4 py-2">Reject</button></div>}
      {request.status === 'APPROVED' && <button onClick={() => { const reason = prompt('Cancellation reason'); if (reason) run(() => cancelApprovedLeaveAction(request.id, reason, true)); }} className="mt-4 rounded-xl border border-rose-300 px-4 py-2 text-rose-700">Cancel and reverse</button>}{request.attendanceSyncStatus === 'FAILED' && <button onClick={() => run(() => retryLeaveAttendanceSyncAction(request.id))} className="ml-2 mt-4 rounded-xl border px-4 py-2">Retry attendance sync</button>}
    </article>)}</section>
  </div>;
}
