import { PrintButton } from './PrintButton';

interface FormRequest { employeeName: string; organizationName: string | null; organizationTimeZone: string; type: string; category: string | null; from: string; to: string; expectedReturnDate: string | null; units: number | null; reason: string; status: string; submittedAt: string; reviewedAt: string | null; reviewerName: string | null }
const date = (value: string) => new Intl.DateTimeFormat('en-PH', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${value}T00:00:00Z`));

export function SagaLeaveForm({ request }: { request: FormRequest }) {
  const filed = new Intl.DateTimeFormat('en-PH', { dateStyle: 'long', timeZone: request.organizationTimeZone }).format(new Date(request.submittedAt));
  const reviewed = request.reviewedAt ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'long', timeStyle: 'short', timeZone: request.organizationTimeZone }).format(new Date(request.reviewedAt)) : null;
  return <div className="space-y-4"><div className="no-print flex justify-end"><PrintButton /></div><article className="leave-form mx-auto max-w-3xl border-2 border-slate-900 bg-white p-8 text-slate-950"><header className="border-b-2 border-slate-900 pb-5 text-center"><p className="text-sm font-bold uppercase tracking-widest">{request.organizationName ?? 'SAGA'}</p><h1 className="mt-2 text-2xl font-black uppercase">Leave Form</h1></header><dl className="mt-6 grid grid-cols-2 gap-x-8 gap-y-5 text-sm"><FormField wide label="Employee Name" value={request.employeeName} /><FormField label="Date Filed" value={filed} /><FormField label="Status" value={request.status} /><FormField label="Leave Date" value={request.from === request.to ? date(request.from) : `${date(request.from)} – ${date(request.to)}`} /><FormField label="Expected Date to Return" value={request.expectedReturnDate ? date(request.expectedReturnDate) : 'Pending schedule calculation'} /><FormField label="No. of Days" value={request.units == null ? 'Pending schedule calculation' : String(request.units)} /><FormField label="Leave Type / Category" value={`${request.type}${request.category ? ` / ${request.category}` : ''}`} /><div className="col-span-2"><dt className="font-bold">Reason</dt><dd className="min-h-24 whitespace-pre-wrap border-b border-slate-700 py-2">{request.reason}</dd></div></dl><div className="mt-16 grid grid-cols-2 gap-16 text-center"><InstitutionalField label="Noted by" /><InstitutionalField label="Approved by" /></div>{request.reviewerName && <aside className="mt-10 border-t pt-4 text-xs text-slate-600"><strong>WorkPulse review metadata:</strong> Reviewed by {request.reviewerName}{reviewed ? ` on ${reviewed}` : ''}. This metadata is not a formal signature.</aside>}</article></div>;
}

function FormField({ label, value, wide = false }: { label: string; value: string; wide?: boolean }) { return <div className={wide ? 'col-span-2' : ''}><dt className="font-bold">{label}</dt><dd className="border-b border-slate-700 py-2">{value}</dd></div>; }
function InstitutionalField({ label }: { label: string }) { return <div><div className="h-12 border-b border-slate-900" /><strong className="mt-2 block">{label}</strong><span className="text-xs text-slate-500">Institutional approval field — no digital signature recorded</span></div>; }
