import { PrintButton } from './PrintButton';

interface FormRequest { employeeName: string; organizationName: string | null; organizationTimeZone: string; type: string; category: string | null; from: string; to: string; expectedReturnDate: string | null; units: number; reason: string; status: string; submittedAt: string; reviewedAt: string | null; reviewerName: string | null }
const date = (value: string) => new Intl.DateTimeFormat('en-PH', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${value}T00:00:00Z`));

export function SagaLeaveForm({ request }: { request: FormRequest }) {
  const filed = new Intl.DateTimeFormat('en-PH', { dateStyle: 'long', timeZone: request.organizationTimeZone }).format(new Date(request.submittedAt));
  const reviewed = request.reviewedAt ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'long', timeStyle: 'short', timeZone: request.organizationTimeZone }).format(new Date(request.reviewedAt)) : null;
  return <div className="space-y-4"><div className="no-print flex justify-end"><PrintButton /></div><article className="leave-form mx-auto max-w-3xl border-2 border-slate-900 bg-white p-8 text-slate-950"><header className="border-b-2 border-slate-900 pb-5 text-center"><p className="text-sm font-bold uppercase tracking-widest">{request.organizationName ?? 'SAGA'}</p><h1 className="mt-2 text-2xl font-black uppercase">Leave Form</h1></header><dl className="mt-6 grid grid-cols-2 gap-x-8 gap-y-5 text-sm"><div className="col-span-2"><dt className="font-bold">Employee Name</dt><dd className="border-b border-slate-700 py-2">{request.employeeName}</dd></div><div><dt className="font-bold">Date Filed</dt><dd className="border-b border-slate-700 py-2">{filed}</dd></div><div><dt className="font-bold">Request Status</dt><dd className="border-b border-slate-700 py-2">{request.status}</dd></div><div><dt className="font-bold">Leave Date</dt><dd className="border-b border-slate-700 py-2">{request.from === request.to ? date(request.from) : `${date(request.from)} – ${date(request.to)}`}</dd></div><div><dt className="font-bold">Expected Date to Return</dt><dd className="border-b border-slate-700 py-2">{request.expectedReturnDate ? date(request.expectedReturnDate) : 'Not reliably determined'}</dd></div><div><dt className="font-bold">No. of Days</dt><dd className="border-b border-slate-700 py-2">{request.units}</dd></div><div><dt className="font-bold">Leave Type / Category</dt><dd className="border-b border-slate-700 py-2">{request.type}{request.category ? ` / ${request.category}` : ''}</dd></div><div className="col-span-2"><dt className="font-bold">Reason</dt><dd className="min-h-24 border-b border-slate-700 py-2 whitespace-pre-wrap">{request.reason}</dd></div></dl><div className="mt-16 grid grid-cols-2 gap-16 text-center"><div><div className="h-12 border-b border-slate-900" /><strong className="mt-2 block">Noted by</strong><span className="text-xs text-slate-500">Institutional approval field — no digital signature recorded</span></div><div><div className="h-12 border-b border-slate-900" /><strong className="mt-2 block">Approved by</strong><span className="text-xs text-slate-500">Institutional approval field — no digital signature recorded</span></div></div>{request.reviewerName && <aside className="mt-10 border-t pt-4 text-xs text-slate-600"><strong>WorkPulse review metadata:</strong> Reviewed by {request.reviewerName}{reviewed ? ` on ${reviewed}` : ''}. This metadata is not a formal signature.</aside>}</article></div>;
}
