import { TenantLogo } from '@/components/layout/TenantLogo';
import type { OrganizationBrandingView } from '@/features/organization-branding/read-model';
import type { PayslipViewModel } from '@/features/payroll/payslip';
import { PayslipPrintButton } from './PayslipPrintButton';

const dateLabel = (value: string) => new Intl.DateTimeFormat('en-PH', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}T00:00:00Z`));
const timestampLabel = (value: string, timeZone: string) => new Intl.DateTimeFormat('en-PH', { dateStyle: 'long', timeStyle: 'short', timeZone }).format(new Date(value));
const money = (value: string, currency: string) => new Intl.NumberFormat('en-PH', { style: 'currency', currency, minimumFractionDigits: 2 }).format(Number(value));

function AmountLine({ label, value, currency, strong = false }: { label: string; value: string; currency: string; strong?: boolean }) {
  return <div className={`flex items-center justify-between gap-4 py-2 ${strong ? 'border-t text-base font-black' : 'text-sm'}`}><dt>{label}</dt><dd className="tabular-nums">{money(value, currency)}</dd></div>;
}

export function PayslipView({ payslip, branding, backHref }: { payslip: PayslipViewModel; branding: OrganizationBrandingView; backHref: string }) {
  const currency = payslip.payroll.currency;
  const attendanceLines = [
    ['Scheduled workdays', payslip.attendance.scheduledWorkdays, 'days'], ['Present', payslip.attendance.presentDays, 'days'],
    ['Absent', payslip.attendance.absentDays, 'days'], ['Late', payslip.attendance.lateOccurrences, 'records'],
    ['Approved leave', payslip.attendance.approvedLeaveDays, 'days'],
  ] as const;
  return <div className="space-y-4">
    <div className="no-print flex items-center justify-between gap-3"><a href={backHref} className="text-sm font-bold text-slate-600">← Back</a><PayslipPrintButton /></div>
    <article className="payslip-print mx-auto max-w-4xl rounded-3xl border bg-white p-6 shadow-sm sm:p-10">
      <header className="flex items-start justify-between gap-6 border-b pb-6"><div className="flex items-center gap-4"><TenantLogo branding={branding} size={64} className="h-16 w-16 rounded-xl object-contain" fallbackClassName="flex h-16 w-16 items-center justify-center rounded-xl bg-slate-900 font-black text-white" /><div><p className="text-xl font-black">{branding.displayName}</p><p className="text-xs text-slate-500">Official Finalized Payslip</p></div></div><div className="text-right text-xs text-slate-500"><p className="font-bold text-slate-900">{payslip.payroll.periodReference}</p><p>Reference: {payslip.payroll.periodId}</p></div></header>
      <section className="grid gap-6 border-b py-6 sm:grid-cols-2"><div><h2 className="text-xs font-black uppercase tracking-wider text-slate-500">Employee</h2><dl className="mt-3 space-y-1 text-sm"><div><dt className="inline text-slate-500">Name: </dt><dd className="inline font-bold">{payslip.employee.name}</dd></div><div><dt className="inline text-slate-500">Employee number: </dt><dd className="inline font-bold">{payslip.employee.employeeNumber}</dd></div>{payslip.employee.department ? <div><dt className="inline text-slate-500">Department: </dt><dd className="inline">{payslip.employee.department}</dd></div> : null}{payslip.employee.position ? <div><dt className="inline text-slate-500">Position: </dt><dd className="inline">{payslip.employee.position}</dd></div> : null}</dl></div><div><h2 className="text-xs font-black uppercase tracking-wider text-slate-500">Payroll</h2><dl className="mt-3 space-y-1 text-sm"><div><dt className="inline text-slate-500">Period: </dt><dd className="inline">{dateLabel(payslip.payroll.periodStart)} – {dateLabel(payslip.payroll.periodEnd)}</dd></div><div><dt className="inline text-slate-500">Pay date: </dt><dd className="inline">{dateLabel(payslip.payroll.payDate)}</dd></div><div><dt className="inline text-slate-500">Compensation: </dt><dd className="inline">{payslip.payroll.compensationType} · {money(payslip.payroll.compensationRate, currency)} · {payslip.payroll.payFrequency}</dd></div></dl></div></section>
      <div className="grid gap-8 py-6 md:grid-cols-2"><section><h2 className="text-xs font-black uppercase tracking-wider text-slate-500">Calculation</h2><dl className="mt-3"><AmountLine label="Base Pay" value={payslip.calculation.basePay} currency={currency} /><AmountLine label="Gross Pay" value={payslip.calculation.grossPay} currency={currency} strong /></dl><h3 className="mt-6 text-xs font-black uppercase tracking-wider text-slate-500">Deductions</h3><dl className="mt-3">{payslip.calculation.deductions.late !== null ? <AmountLine label="Late" value={payslip.calculation.deductions.late} currency={currency} /> : null}{payslip.calculation.deductions.absence !== null ? <AmountLine label="Absence" value={payslip.calculation.deductions.absence} currency={currency} /> : null}{payslip.calculation.deductions.undertime !== null ? <AmountLine label="Undertime" value={payslip.calculation.deductions.undertime} currency={currency} /> : null}<AmountLine label="Total Deductions" value={payslip.calculation.totalDeductions} currency={currency} strong /><AmountLine label="Net Pay" value={payslip.calculation.netPay} currency={currency} strong /></dl></section>
        <section><h2 className="text-xs font-black uppercase tracking-wider text-slate-500">Attendance Summary</h2><dl className="mt-3 divide-y">{attendanceLines.filter(([, value]) => value !== null).map(([label, value, unit]) => <div key={label} className="flex justify-between py-2 text-sm"><dt>{label}</dt><dd className="font-bold">{value} {unit}</dd></div>)}</dl>{payslip.leaveTreatments.length ? <><h3 className="mt-6 text-xs font-black uppercase tracking-wider text-slate-500">Leave Treatment</h3><ul className="mt-3 space-y-2 text-sm">{payslip.leaveTreatments.map((item, index) => <li key={`${item.typeName}-${index}`} className="flex justify-between gap-3"><span>{item.typeName}</span><span className="font-bold">{item.treatment.replaceAll('_', ' ')}</span></li>)}</ul></> : null}</section></div>
      <footer className="border-t pt-5 text-xs text-slate-500"><p>Finalized: {timestampLabel(payslip.payroll.finalizedAt, branding.timeZone)}</p><p className="mt-1">This payslip is rendered from the finalized payroll calculation snapshot.</p></footer>
    </article>
  </div>;
}
