import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getMyLeaveRequest } from '@/features/leave/self-queries';
import { removeMyLeaveDocumentAction, uploadMyLeaveDocumentAction, withdrawMyLeaveRequestAction } from '@/features/leave/self-actions';

export default async function MyLeaveRequestPage({ params }: { params: Promise<{ requestId: string }> }) {
  const { requestId } = await params; const request = await getMyLeaveRequest(requestId); if (!request) notFound();
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><h1 className="text-2xl font-black">{request.type}</h1><Link href={`/employee/leave/${request.id}/form`} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">View / Print Leave Form</Link></div><section className="rounded-3xl border bg-white p-6 text-sm"><p>{request.from}–{request.to} · {request.units} unit(s)</p><p className="mt-2">Status: <strong>{request.status}</strong></p><p className="mt-2">{request.reason}</p></section><section className="rounded-3xl border bg-white p-6"><h2 className="font-bold">Supporting documents</h2>{request.documents.map((doc) => <div className="flex flex-wrap items-center gap-2" key={doc.id}><a className="text-blue-700 underline" href={`/api/leave-documents/${doc.id}`}>{doc.kindCode}: {doc.fileName}</a>{request.status === 'PENDING' && <form action={async () => { 'use server'; await removeMyLeaveDocumentAction(request.id, doc.id, true); }}><button className="text-sm text-rose-700">Remove</button></form>}</div>)}{request.status === 'PENDING' && <form className="mt-4 flex flex-wrap gap-2" action={async (formData) => { 'use server'; await uploadMyLeaveDocumentAction(request.id, formData); }}><select name="kindCode" className="rounded-xl border p-2"><option value="SUPPORTING_DOCUMENT">Supporting document</option><option value="MEDICAL_CERTIFICATE">Medical certificate</option><option value="SSS_SUPPORT">SSS approval/support</option></select><input type="file" name="file" required accept=".pdf,image/jpeg,image/png,image/webp" /><button className="rounded-xl bg-slate-900 px-4 py-2 text-white">Upload document</button></form>}</section>{request.status === 'PENDING' && <form action={async () => { 'use server'; await withdrawMyLeaveRequestAction(request.id, true); }}><button className="rounded-xl border border-rose-300 px-4 py-2 text-rose-700">Withdraw pending request</button></form>}</div>;
}
