import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { requireBackOfficeContext } from '@/lib/auth/guards';
import { canViewOrganizationLeave } from '@/lib/permissions/rbac';
import { getLeaveAdminRequest } from '@/features/leave/hr-queries';
import { LeaveReviewPanel } from '@/components/leave/LeaveReviewPanel';
import { cancelApprovedLeaveAction, retryLeaveAttendanceSyncAction } from '@/features/leave/hr-actions';

export default async function LeaveRequestDetailPage({ params }: { params: Promise<{ requestId: string }> }) { const user = await requireBackOfficeContext(); if (!canViewOrganizationLeave(user)) redirect('/dashboard'); const { requestId } = await params; const request = await getLeaveAdminRequest(user.organizationId, requestId); if (!request) notFound(); return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/dashboard/leave" className="text-sm underline">Back to Leave Management</Link><h1 className="mt-2 text-2xl font-black">{request.employeeName}</h1><p className="text-sm text-slate-500">{request.employee.employeeNumber} · {request.type}{request.category ? ` · ${request.category}` : ''}</p></div><Link href={`/dashboard/leave/requests/${request.id}/form`} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">View / Print Leave Form</Link></div><section className="grid gap-4 rounded-3xl border bg-white p-6 text-sm md:grid-cols-2"><div><strong>Date range</strong><p>{request.from}–{request.to}</p></div><div><strong>Requested units</strong><p>{request.units}</p></div><div><strong>Submitted</strong><p>{new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: request.organizationTimeZone }).format(new Date(request.submittedAt))}</p></div><div><strong>Status</strong><p>{request.status}</p></div><div className="md:col-span-2"><strong>Reason</strong><p className="whitespace-pre-wrap">{request.reason}</p></div><div className="md:col-span-2"><strong>Supporting documents</strong><div>{request.documents.length ? request.documents.map((document) => <a key={document.id} className="mr-3 text-blue-700 underline" href={`/api/leave-documents/${document.id}`}>{document.kindCode}: {document.fileName}</a>) : <p>None attached</p>}</div></div></section>{request.status === 'PENDING' && <LeaveReviewPanel requestId={request.id} typeCode={request.typeCode} />}{request.status === 'APPROVED' && <form action={async () => { 'use server'; await cancelApprovedLeaveAction(request.id, 'Cancelled by HR from request detail.', true); }}><button className="rounded-xl border border-rose-300 px-4 py-2 text-rose-700">Cancel and Reverse</button></form>}{request.attendanceSyncStatus === 'FAILED' && <form action={async () => { 'use server'; await retryLeaveAttendanceSyncAction(request.id); }}><button className="rounded-xl border px-4 py-2">Retry Attendance Sync</button></form>}</div>; }
